### ISSUE TITLE
some contents seem to be significant for conducting symbolic music generation tasks

### ISSUE THREAD

**Issue by atsukoba** [yamathcy/awesome-music-infomatics#2]
Hi, @yamathcy-san. Thank you for creating this awesome awesome-repo and sharing your knowledge!

I propose some contents: a book, a review paper, and OSS tools that seem to be significant for conducting symbolic music generation tasks.

## libraries

- miditoolkit: <https://github.com/YatingMusic/miditoolkit> MIDI parser for handling both eventswith symbolic timing and piano-rolls
- note_seq <https://github.com/magenta/note-seq> MIDI data manipulating and converting for for ML model training (e.g., one-hot tensors)

## book

- Deep Learning Techniques for Music Generation: <https://link.springer.com/book/10.1007/978-3-319-70163-9>

## review papers

- Music Composition with Deep Learning: A Review, Hernandez-Olivan et al., 2021 <https://arxiv.org/abs/2108.12290>

**Comment by yamathcy** [comment]
Hi, thank you for sharing the information!
I just added them.
